### ISSUE TITLE
Ruby on Rails in Xems

### ISSUE THREAD

**Issue by po1206** [po1206/xems#2]
### Discussed in https://github.com/po1206/xems/discussions/1

<div type='discussions-op-text'>

<sup>Originally posted by **po1206** June  3, 2024</sup>

## 👋 Welcome!
  We’re using Discussions as a place to connect with other members of our community. We hope that you:
  * Ask questions you’re wondering about.
  * Share ideas.
  * Engage with other community members.
  * Welcome others and are open-minded. Remember that this is a community we
  build together 💪.

  To get started, comment below with an introduction of yourself and tell us about what you do with this community.

</div>

**Comment by hotcoding85** [comment]
Hi,

1. Make sure if you already installed Ruby (vx.y.z).
2. Also make sure if the mysql or postgresql is installed in you PC.
3. To install Rails, use the gem install command provided by RubyGems: `gem install rails`
4. To use this generator, open a terminal, navigate to a directory where you have rights to create files, and run: `rails new blog`

Feel free to reach out if there is any other problem for me.
